# Generated by Django 4.0.3 on 2022-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('maxdis', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
