# Generated by Django 4.0.3 on 2022-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('verified', models.CharField(default='no', max_length=100)),
            ],
        ),
    ]
