# Generated by Django 4.0.3 on 2022-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contactno',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
