# Generated by Django 4.0.3 on 2022-05-24 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='maxdis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Flightroutes',
            fields=[
                ('routeno', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='booking.places')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='booking.places')),
            ],
        ),
    ]
