# Generated by Django 4.0.3 on 2022-05-24 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_offers_id_alter_offers_maxdis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightno', models.CharField(max_length=10, unique=True)),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('basefare', models.IntegerField()),
                ('routeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_route', to='booking.flightroutes')),
            ],
        ),
    ]
