# Generated by Django 4.0.3 on 2022-05-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_flights_routeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='routeno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routen', to='booking.flightroutes'),
        ),
    ]
