# Generated by Django 4.0.3 on 2022-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_flights_arrival_alter_flights_departure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('flightdate', models.CharField(max_length=15)),
                ('flightno', models.CharField(max_length=10)),
                ('booking', models.IntegerField(max_length=10, unique=True)),
                ('paidamt', models.IntegerField(max_length=10)),
            ],
        ),
    ]
