# Generated by Django 4.0.3 on 2022-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('bookingID', models.IntegerField(max_length=10, unique=True)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_status', to='booking.ticket')),
            ],
        ),
    ]
