# Generated by Django 4.0.3 on 2022-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_passenger_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
