# Generated by Django 4.0.3 on 2022-05-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_ticket_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure',
            field=models.TimeField(),
        ),
    ]
